# Generated by Django 4.1.11 on 2023-11-07 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="additional",
        ),
    ]
