# Generated by Django 4.1.11 on 2023-11-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0002_remove_faq_additional"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="information",
            field=models.TextField(blank=True),
        ),
    ]
