# Generated by Django 4.1.11 on 2023-11-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0003_project_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_repo",
            field=models.TextField(blank=True),
        ),
    ]
