# Generated by Django 4.1.11 on 2023-11-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0004_user_token_repo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="repo_login",
            field=models.BooleanField(default=False),
        ),
    ]
