# Generated by Django 4.1.11 on 2023-11-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0005_user_repo_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_Loading",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="is_Loading",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
