# Generated by Django 4.1.11 on 2023-11-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0006_asset_is_loading_project_is_loading"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="root",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
