# Generated by Django 4.1.11 on 2023-11-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0007_project_root"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="latest_build",
            field=models.DateTimeField(blank=True, default=""),
        ),
    ]
