# Generated by Django 4.1.11 on 2023-11-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0008_alter_project_latest_build"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="message_failed",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="asset",
            name="to_failed",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
