# Generated by Django 4.1.11 on 2023-11-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0009_asset_message_failed_asset_to_failed"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="urls",
            field=models.TextField(blank=True, default=""),
        ),
    ]
