# Generated by Django 4.1.11 on 2024-04-15 14:27

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0012_asset_short_sha_asset_url_commit"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="lang",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="asset",
            name="privacy",
            field=models.CharField(blank=True, default="private", max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="lang",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="last_short_sha",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="template",
            field=models.TextField(blank=True, default="default"),
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("user_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "projects",
                    djongo.models.fields.ArrayReferenceField(
                        blank=True,
                        default=list,
                        on_delete=djongo.models.fields.ArrayReferenceField._on_delete,
                        to="codeia.project",
                    ),
                ),
            ],
        ),
    ]
