# Generated by Django 4.1.11 on 2024-04-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0013_asset_lang_asset_privacy_project_lang_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="user_id",
            field=models.IntegerField(blank=True),
        ),
    ]
