# Generated by Django 4.1.11 on 2024-04-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0014_alter_repository_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="nationality",
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
