# Generated by Django 4.1.11 on 2024-04-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0015_remove_user_nationality_user_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
        migrations.AddField(
            model_name="user",
            name="is_unverified",
            field=models.BooleanField(default=True),
        ),
    ]
