# Generated by Django 4.1.11 on 2024-04-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0016_remove_user_is_verified_user_is_unverified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
