# Generated by Django 4.1.11 on 2024-04-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0017_user_verification_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="two_factor",
            field=models.BooleanField(default=False),
        ),
    ]
