# Generated by Django 4.1.11 on 2024-04-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0018_user_two_factor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forgotten",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
