# Generated by Django 4.1.11 on 2024-04-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "codeia",
            "0020_asset_theme_project_serializer_info_project_url_info_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="guide_running",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
