# Generated by Django 4.1.11 on 2024-05-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0021_project_guide_running"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_github",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
