# Generated by Django 4.1.11 on 2024-05-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeia", "0023_star_asset_stars"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_plan", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("months_duration", models.IntegerField()),
                ("activation_code", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(blank=True, max_length=100)),
                ("is_activated", models.BooleanField(blank=True, default=False)),
                ("due_date", models.DateTimeField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
